# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 11:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rainbow', '0004_auto_20170820_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='state',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
