# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 18:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainbow', '0006_player_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
